---
apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: oauth-proxy-template
message: |-
  Operator has been deployed
metadata:
  name: oauth-proxy-template
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: oauth-proxy
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: oauth-proxy
    template:
      metadata:
        labels:
          name: oauth-proxy
      spec:
        serviceAccountName: itcm-ngm-sa
        containers:
          - name: oauth-proxy-test
            # Replace this with the built image name
            image: docker-registry.default.svc:5000/${NAMESPACE}/oauth-proxy
            command:
            - oauth-proxy
            imagePullPolicy: Always
            env:
              - name: WATCH_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
parameters:
  - description: Namespace
    displayName: Namespace
    name: NAMESPACE
    value: oauth-proxy

